### ISSUE TITLE
Add functions areItemsTheSame and areContentsTheSame to FoodInstance

### ISSUE THREAD

**Issue by raphelkabir** [KabSoft-Team/Slurp#34]
areItemsTheSame should return true if the two items have the same id/reference
areContentsTheSame should return true if the two items members have the same value

**Comment by LucaFalasca** [comment]
Per controllare che due Item puntino allo stesso oggetto basta usare l'operatore ==

Normalmente per controllare che due oggetti siano funzionalmente uguali di usa il metodo equals (basta pensare al confronto tra stringhe). Di base l'operatore equals è definito tramite == ma è opportuno cambiarlo in base all'oggetto. Quindi per l'operazione areContentsTheSame basterà usare il metodo equals.

Fonti :
- http://informatica.abaluth.com/programmazione/java/java-metodo-equals/
- https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)


Ora sorge un dilemma che dipende da come vogliamo interpretarlo e da cosa ti serve. 
FoodInstance ha 3 attributi:
- FoodType
- Data
- PortionsConsumed

Siccome i primi due compongono la chiave primaria nel Database non esisteranno mai 2 instanze con stessa coppia (FoodType, Data), e quindi in linea di principio basterebbe controllare questi due attributi per definire uguali due oggetti di questo tipo, anche considerando il fatto che PortionsConsumed è un attributo che cambierà spesso durante la vita dell'app. Tuttavia a te potrebbe servirti il controllo su tutti e tre gli attributi insieme e quindi potrebbe aver senso ridefinire il metodo equals in questa ottica.

Dimmi cosa ne pensi e cosa serve a te

**Comment by LucaFalasca** [comment]
Equals è stato implementato con il controllo su tutti e tre gli attributi
