### ISSUE TITLE
DailyFragment should getFoodTypesByFrequency instead of getFoodInstances

### ISSUE THREAD

**Issue by raphelkabir** [KabSoft-Team/Slurp#37]

**Comment by LucaFalasca** [comment]
Non ho capito cosa intendi con questo ticket @raphelkabir

**Comment by raphelkabir** [comment]
Ah scusa avrei dovuto assegnare questo a me stesso

**Comment by LucaFalasca** [comment]
ok, però cerca comunque di essere più chiaro nelle descrizioni dei ticket

**Comment by raphelkabir** [comment]
Sure :P
