### ISSUE TITLE
Wrong return type of getFoodTypesByFrequency

### ISSUE THREAD

**Issue by raphelkabir** [KabSoft-Team/Slurp#38]
getFoodTypesByFrequency was supposed to return an array of FoodInstance, instead it's returning the old FoodType

**Comment by LucaFalasca** [comment]
Ah no, in realtà se vedi lui ritorna i food Types. L'idea era di riempire questa parte qui
![107665142-725fc680-6c8d-11eb-84f0-23f7b35f97ac](https://user-images.githubusercontent.com/30274870/119023455-33cf5b80-b9a2-11eb-9920-04c97f4ea922.png)

Quello che ti serve è un metodo che ritorna una FoodInstance dato un parametro FoodType e una data

**Comment by LucaFalasca** [comment]
@raphelkabir

**Comment by LucaFalasca** [comment]
é opportuno usare le label quando si creano i Ticket @raphelkabir

**Comment by raphelkabir** [comment]
Kk
