### ISSUE TITLE
Unexpected behaviour from plus and minus button

### ISSUE THREAD

**Issue by raphelkabir** [KabSoft-Team/Slurp#58]

**Comment by LucaFalasca** [comment]
Scusa, ma perchè il commit e il ticket hanno due nomi diversi?

**Comment by LucaFalasca** [comment]
@raphelkabir

**Comment by raphelkabir** [comment]
Nel ticket c'e' scritto il problema mentre nel commit c'e' scritto la soluzione

**Comment by LucaFalasca** [comment]
Sarebbe meglio scrivere tutto nel ticket, magari con un commento separato

**Comment by raphelkabir** [comment]
Hm non saprei, i ticket li vedo come qualcosa di neutrale perche' alla fine possono essere fatti da tutti quanti cosi' diciamo che sono piu' accessibile? Mentre il commit e' piu' una risposta.
E' vero che io ho fatto il ticket e il commit praticamente insieme ma teoricamente il ticket bisogna farlo prima, e il commit dovrebbe venire molto dopo.

**Comment by LucaFalasca** [comment]
Si è vero, per questo è meglio scrivere un commento sul ticket. In questo modo rimane la cronologia del problema nel tempo ed è anche più facile da vedere perché è tutto insieme

**Comment by raphelkabir** [comment]
E' meglio anche per consistenza perche' alla fine dei conti chi fa i ticket e chi fa i commit non sono sempre la stessa persona infatti molte volte i miei ticket li hai fatti tu

**Comment by LucaFalasca** [comment]
Eh ma nei commenti del ticket comunque c'è scritto chi ha commentato

**Comment by raphelkabir** [comment]
Mi dispiace non capisco come si collega al commento precedente

**Comment by raphelkabir** [comment]
Commento carina la sezione notificazione di Github
