### ISSUE TITLE
refactoring/beautifying

### ISSUE THREAD

**Issue by raphelkabir** [KabSoft-Team/Slurp#59]
Removed unused piece of codes, improved indentation and generally improved readability

**Comment by LucaFalasca** [comment]
@raphelkabir le devi mettere le descrizioni, ti uccido

**Comment by raphelkabir** [comment]
Ma non c'era bisogno

**Comment by LucaFalasca** [comment]
Certo che c'è bisogno, altrimenti io non capisco facilmente cosa hai fatto

**Comment by raphelkabir** [comment]
Cerco di tenerlo a mente piu' spesso :P
