### ISSUE TITLE
Remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories

### ISSUE THREAD

**Issue by LucaFalasca** [KabSoft-Team/Slurp#71]
Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'Slurp', project ':app'
Affected Modules: app

**Comment by raphelkabir** [comment]
Ops
